# **ASSIGNMENT_004**
 ## **FSDS Batch 17 September 2022**

**Q1. Find the largest number from the given list, use for loop.**

```
numbers = [12, 75, 150, 180, 145, 525, 50]
```

In [ ]:
numbers = [12, 75, 150, 180, 145, 525, 50]
max = numbers[0] 
for num in numbers:
  if num > max:
    max = num
print(f"The Largest number from the given list is:{max}")

The Largest number from the given list is:525

**Q2. Print all the even number between (1, 12).**

In [ ]:
for i in range(1,12):
  if i % 2 == 0:
    print(f"All the even number between (1,12) are: {i}")

All the even number between (1,12) are: 2
All the even number between (1,12) are: 4
All the even number between (1,12) are: 6
All the even number between (1,12) are: 8
All the even number between (1,12) are: 10

**Q3. Calculate the sum of all numbers from 1 to a given number**
```
    
    Expected Output:

    Enter number 10
    
    Sum is:  55

```

In [ ]:
n = int(input("The given number is: "))
sum = 0 
for i in range(1,n+1):
  sum = sum + i
print(f"The sum of all numbers from 1 to given number is: {sum}")

The given number is: 10
The sum of all numbers from 1 to given number is: 55

**Q4. Write a program to display only those numbers from a list that satisfy the following conditions**

- The number must be divisible by five

- If the number is greater than 150, then skip it and move to the next number

- If the number is greater than 500, then stop the loop

In [ ]:
a = [12, 75, 150, 180, 145, 525, 50]
for i in a:
  if i > 150:
    if i > 500:
      break
    continue
  if i % 5 == 0:
    print(i, end=" ")

75 150 145

**Q5. Print the given list in reverse order.**

```
list1 = [10, 20, 30, 40, 50]

```

In [ ]:
list1 = [10, 20, 30, 40, 50]
print(f"The given list in reverse order is: {list1[::-1]}")

The given list in reverse order is: [50, 40, 30, 20, 10]